on:
  push: {}
  pull_request: {}

name: Build CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build toplevel project
        run: gradle build --info

      - name: Build android project
        run: gradle build --info
        working-directory: android

      - name: Upload apk
        run: |
          find /usr/local/lib/android/sdk/
          whereis apk-signer
