on:
  push: {}
  pull_request: {}

name: Build CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build toplevel project
        run: gradle build --info

      - name: Build android project
        run: gradle build --info
        working-directory: android

      - name: Android SDK path setup
        run: bash .scripts/android-sdk.sh

      - name: Resign apks
        run: bash .scripts/ci-dummy-sign.sh

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build/output
