on:
  release:
    types: [ published ]

name: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 18

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
          gradle-version: 7.6

      - name: Build toplevel project
        run: gradle build buildPlugin updateAndroidProperties dump-ci-helper-cli --info

      - name: Build android project
        run: gradle build --info
        working-directory: android

      - name: Android SDK path setup
        run: bash .scripts/android-sdk.sh

      - name: Write Cert
        run: bash .scripts/write-cert.sh
        env:
          CERT_CERTFILE: ${{ secrets.CERT_CERTFILE }}
          CERT_KEYFILE: ${{  secrets.CERT_KEYFILE  }}

      - name: Resign apks
        run: bash .scripts/ci-dummy-sign.sh

      - name: Upload assets to release
        run: sh .scripts/ci-helper.sh uploadAssets
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOAD_URL: ${{ github.event.release.upload_url }}

#          // /repos/{owner}/{repo}/releases/{release_id}/assets
